/**
 * PreToolUse on Edit and Write: the files nobody hand-edits, with the reason
 * each time so the model does the right thing instead.
 *
 * Answers with the JSON deny shape rather than exit 2 so the reason reaches
 * the model verbatim and the turn continues.
 */
import { readInput, repoRelative } from "./lib.mjs";

const PROTECTED = new Map([
  [
    "src/routeTree.gen.ts",
    "generated by the TanStack Router plugin; boot `npm run dev` to regenerate it (docs/QUIRKS.md, Generated route tree)",
  ],
  [
    "src/db/auth-schema.ts",
    "generated by the Better Auth CLI; change `additionalFields` in the auth config and regenerate (docs/QUIRKS.md, Better Auth)",
  ],
  ["CLAUDE.md", "a symlink to AGENTS.md; edit AGENTS.md"],
  [".env", "personal, untracked config; tell the user what to set"],
  [".env.local", "personal, untracked config; tell the user what to set"],
]);

const input = readInput();
const cwd = input.cwd ?? process.cwd();
const path = repoRelative(cwd, input.tool_input?.file_path ?? "");
const reason = PROTECTED.get(path);

if (reason) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `${path} is ${reason}.`,
      },
    })
  );
}
