services:
  postgres:
    image: postgres:18
    container_name: cs-capstone-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cs_capstone
    volumes:
      - postgres_data:/var/lib/postgresql

  rustfs:
    image: rustfs/rustfs:latest
    container_name: cs-capstone-storage
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console/UI (if available)
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - s3_data:/data
volumes:
  postgres_data:
  s3_data: