#!/usr/bin/env bash
#
# Walks a new colleague through the parts of local setup only a person can do,
# from a fresh clone to every test suite green. Run it from the repo root:
#
#   bash scripts/onboard.sh
#
# Re-runnable: values already in .env.local are offered as defaults, the
# migrations and seeds are idempotent, and Ctrl-C then a re-run resumes.
# docs/ONBOARDING.md is the prose around it.
#
# Generated by the /wizard skill. Everything above the "STAGES" marker is the
# wizard library, identical across wizards, with one local change: the check
# mark and warning sign glyphs are words, because this repo's prose rule
# (AGENTS.md, scripts/check-prose.mjs) rejects them in tracked files.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %swarning: %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %sok, wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %sok, set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %sok, set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# The app and every script read .env.local; docker compose reads .env.
ENV_FILE=.env.local

# run_suite "label" cmd... runs one test suite and stops the wizard on red,
# naming the QUIRKS section that explains most red runs here. The suites are
# the whole point of the last stage, so a failure is the wizard's failure.
run_suite() {
  local label="$1"; shift
  say ""
  say "${BOLD}$label${RESET}: $*"
  if "$@"; then
    printf '  %sok, %s green%s\n' "$GREEN" "$label" "$RESET"
  else
    printf '\n  %s%s failed.%s\n' "$RED" "$label" "$RESET"
    note "Read the Vitest section of docs/QUIRKS.md before anything else: the"
    note "Node version, the sandbox, and the shared dev database are the usual"
    note "causes. Fix it, then re-run this wizard; it skips nothing but costs"
    note "only the re-run."
    exit 1
  fi
}

if [[ ! -f package.json || ! -f .nvmrc ]]; then
  printf 'Run this from the repository root: bash scripts/onboard.sh\n' >&2
  exit 1
fi

banner "EECS Capstone: first-day setup"

# ── Stage 1: the Node in .nvmrc ────────────────────────────────────────────
stage "Node"
WANTED=$(tr -d '[:space:]' < .nvmrc)
say "The tests need the Node in .nvmrc ($WANTED). Another major looks fine"
say "and then fails about 65 unit tests on localStorage (docs/QUIRKS.md,"
say "\"Run the tests on the Node in .nvmrc\")."
# nvm.sh is not written for `set -u`, so it is sourced with that relaxed.
set +u
if [[ -s "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]]; then
  # shellcheck disable=SC1091
  source "${NVM_DIR:-$HOME/.nvm}/nvm.sh" >/dev/null 2>&1 || true
  nvm install >/dev/null 2>&1 || true
  nvm use >/dev/null 2>&1 || true
elif command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env)" >/dev/null 2>&1 || true
  fnm install >/dev/null 2>&1 || true
  fnm use >/dev/null 2>&1 || true
fi
set -u
RUNNING=$(node --version 2>/dev/null | sed 's/^v//' || true)
if [[ "${RUNNING%%.*}" != "${WANTED%%.*}" ]]; then
  warn "node is ${RUNNING:-missing}, .nvmrc wants $WANTED."
  step "Install nvm (https://github.com/nvm-sh/nvm) or fnm, then run: nvm install"
  step "Open a new shell so the switch takes, and re-run this wizard."
  exit 1
fi
say "node $RUNNING, matches .nvmrc."
say ""
say "Installing dependencies. This also installs the git hooks (lefthook) that"
say "run Biome and the prose check at commit, and typecheck and the unit suite"
say "at push."
npm install
pause

# ── Stage 2: docker ────────────────────────────────────────────────────────
stage "Postgres and object storage"
say "docker compose starts Postgres (pgvector) on 5432 and RustFS, the local"
say "S3, on 9000 and 9001."
if ! docker info >/dev/null 2>&1; then
  warn "docker is not running."
  step "Install Docker Desktop (or another docker engine), start it, re-run."
  exit 1
fi
if docker ps --format '{{.Names}}' | grep -qx cs-capstone-database \
  && [[ -z "$(docker compose ps -q postgres 2>/dev/null)" ]]; then
  warn "cs-capstone-database is already running from another checkout of this repo."
  say "Reusing it. docker-compose.yml fixes the container names, so two checkouts"
  say "cannot each run a stack. If that checkout moved the ports in its .env,"
  say "mirror them in this .env.local (README.md, \"Port conflicts\") before the"
  say "migration stage; the PORTS column below says which."
  docker ps --filter name=cs-capstone
else
  docker compose up -d
  say ""
  say "Check the PUBLISHED PORTS column below is not empty. If another project"
  say "already holds 5432 or 9000, the containers start and publish nothing,"
  say "and the app talks to the other project's database. README.md, \"Port"
  say "conflicts\", says how to move this stack to other ports in .env."
  docker compose ps
fi
pause "Ports look right?"

# ── Stage 3: .env.local ────────────────────────────────────────────────────
stage "Local configuration"
if [[ -f .env.local ]]; then
  say ".env.local exists; keeping it. Values below default to what it holds."
else
  cp .env.example .env.local
  say "Copied .env.example to .env.local. The defaults match docker compose,"
  say "so nothing else needs editing to run the app."
fi
say ""
say "Better Auth needs a secret. Generating one with the Better Auth CLI."
GENERATED=$(npx -y @better-auth/cli secret 2>/dev/null | sed -n 's/^BETTER_AUTH_SECRET=//p' | tail -n1 || true)
CURRENT=$(_existing BETTER_AUTH_SECRET || true)
if [[ -n "$CURRENT" && "$CURRENT" != "replace-me-run-npx-better-auth-cli-secret" ]]; then
  say "BETTER_AUTH_SECRET is already set; keeping it."
elif [[ -n "$GENERATED" ]]; then
  write_env BETTER_AUTH_SECRET "$GENERATED"
else
  warn "the CLI printed nothing; paste a secret by hand."
  step "Run: npx -y @better-auth/cli secret"
  ask_secret BETTER_AUTH_SECRET "Paste the value after BETTER_AUTH_SECRET=:"
  write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
fi
pause

# ── Stage 4: GitHub sign-in, optional ──────────────────────────────────────
stage "GitHub sign-in (optional)"
say "Email and password sign-in works with no provider configured, and the"
say "seeded accounts use it. Register a GitHub OAuth app only if you want to"
say "test that button. ONID sign-in needs nothing from you: UIT registered"
say "the app, the public values are already in .env.local, and the secret"
say "stays with the maintainer (docs/ONID-SSO.md)."
if confirm "Register a GitHub OAuth app now?"; then
  open_url "https://github.com/settings/developers"
  step "OAuth Apps, New OAuth App."
  step "Homepage URL: http://localhost:3000"
  step "Authorization callback URL: http://localhost:3000/api/auth/callback/github"
  step "Register, then copy the Client ID; Generate a new client secret and copy it."
  ask GITHUB_CLIENT_ID "Paste the Client ID:"
  ask_secret GITHUB_CLIENT_SECRET "Paste the client secret:"
  write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
  write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"
else
  note "Skipped. Re-run the wizard any time to add it."
fi
pause

# ── Stage 5: schema and bucket ─────────────────────────────────────────────
stage "Migrations and the bucket"
say "Nothing applies migrations on boot, and the RustFS container starts with"
say "no bucket. Both commands are idempotent."
npm run db:migrate
npm run storage:init
pause

# ── Stage 6: seed ──────────────────────────────────────────────────────────
stage "Seed data"
say "The dev seed creates three accounts, all with the password \"password\":"
say "  user@example.com, instructor@example.com, admin@example.com"
say "plus programs, categories, projects and an inventory with holds in every"
say "state. It drives the real write path, so what you see is what the app"
say "does. Safe to re-run."
npm run db:seed:dev
pause

# ── Stage 7: browser ───────────────────────────────────────────────────────
stage "Playwright browser"
say "The smoke and accessibility suites drive Chromium. One-time download."
npx playwright install chromium
pause

# ── Stage 8: every suite once ──────────────────────────────────────────────
stage "Every suite, once"
say "Four suites, in the order that leaves the database usable at the end."
say ""
say "The integration suite TRUNCATES the dev database before each test"
say "(docs/adr/0011), so the seed runs again after it. The smoke suite builds"
say "the production output and runs it on port 3001; the accessibility smoke"
say "starts the dev server on 3000. Stop any dev server you have running on"
say "3000 first. Expect ten to fifteen minutes."
say ""
say "Two lines every Vitest run prints here and which mean nothing:"
say "  module is not defined"
say "  Tests closed successfully but something prevents Vite server from exiting"
pause "Ready? Enter to run them."
run_suite "unit suite" npm test
run_suite "integration suite" npm run test:integration
say ""
say "Reseeding, because the integration suite emptied the database."
npm run db:seed:dev
run_suite "smoke suite" npm run test:smoke
run_suite "accessibility smoke suite" npm run test:accessibility:smoke
say ""
say "All four green. The end-to-end run leaves E2E- rows behind by design;"
say "sweeping them so the next accessibility run starts clean."
npm run test:e2e:sweep
pause

# ── Stage 9: Claude Code ───────────────────────────────────────────────────
stage "Claude Code (optional)"
say "The repo is set up for Claude Code: .claude/settings.json enables the"
say "mattpocock-skills plugin and installs the hooks under .claude/hooks/."
say "docs/ONBOARDING.md, \"Claude Code\", walks through what you will see:"
step "Install: the desktop app, or npm install -g @anthropic-ai/claude-code."
step "Run \"claude\" in this directory. It asks once whether to trust the"
step "  claude-plugins-official marketplace; answer yes, or the review skill"
step "  every PR needs is not available."
step "The session starts by printing the branch, working tree, Node and"
step "  compose state. That is .claude/hooks/session-context.mjs working."
note "Nothing to capture here."
pause

finish
say "Next: npm run dev, sign in as admin@example.com, and read"
say "docs/ONBOARDING.md for the first week."
