import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "@playwright/test";
import { checkA11y } from "./helpers";

const __dirname = dirname(fileURLToPath(import.meta.url));

// .fixtures.json is generated by global-setup.ts — run `npm run test:accessibility` to populate it.
const { itemId, categoryId, programId, userId } = JSON.parse(
  readFileSync(join(__dirname, ".fixtures.json"), "utf-8")
) as {
  itemId: string;
  categoryId: string;
  programId: string;
  userId: string;
};

test.use({ storageState: join(__dirname, ".admin-auth.json") });

test("admin dashboard", async ({ page }) => {
  await page.goto("/admin");
  await checkA11y(page);
});

test("admin inventory list", async ({ page }) => {
  await page.goto("/admin/inventory");
  await checkA11y(page);
});

test("admin inventory new", async ({ page }) => {
  await page.goto("/admin/inventory/new");
  await checkA11y(page);
});

test("admin inventory item detail", async ({ page }) => {
  await page.goto(`/admin/inventory/${itemId}`);
  await checkA11y(page);
});

test("admin inventory item edit", async ({ page }) => {
  await page.goto(`/admin/inventory/${itemId}/edit`);
  await checkA11y(page);
});

test("admin inventory requests", async ({ page }) => {
  await page.goto("/admin/inventory/requests");
  await checkA11y(page);
});

test("admin projects list", async ({ page }) => {
  await page.goto("/admin/projects");
  await checkA11y(page);
});

test("admin users list", async ({ page }) => {
  await page.goto("/admin/users");
  await checkA11y(page);
});

test("admin user detail", async ({ page }) => {
  await page.goto(`/admin/users/${userId}`);
  await checkA11y(page);
});

test("admin categories list", async ({ page }) => {
  await page.goto("/admin/categories");
  await checkA11y(page);
});

test("admin category detail", async ({ page }) => {
  await page.goto(`/admin/categories/${categoryId}`);
  await checkA11y(page);
});

test("admin programs list", async ({ page }) => {
  await page.goto("/admin/programs");
  await checkA11y(page);
});

test("admin program detail", async ({ page }) => {
  await page.goto(`/admin/programs/${programId}`);
  await checkA11y(page);
});

test("admin mentors list", async ({ page }) => {
  await page.goto("/admin/mentors");
  await checkA11y(page);
});
