import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Page } from "@playwright/test";
import { expect, test } from "@playwright/test";
import { config as loadDotenv } from "dotenv";
import { eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
// biome-ignore lint/performance/noNamespaceImport: drizzle needs the schema namespace object
import * as schema from "../../db/schema";
import { checkA11y, closeMenu, waitForHydration } from "./helpers";

const __dirname = dirname(fileURLToPath(import.meta.url));

// .fixtures.json is generated by global-setup.ts: run `npm run test:accessibility` to populate it.
const { itemId, categoryId, programId, userId } = JSON.parse(
  readFileSync(join(__dirname, ".fixtures.json"), "utf-8")
) as {
  itemId: string;
  categoryId: string;
  programId: string;
  userId: string;
};

test.use({ storageState: join(__dirname, ".admin-auth.json") });

// DB access for the create-dialog coverage further down: those tests write a
// row through the UI and need to remove it afterward, which is not something
// a page.goto() can do. Loaded lazily (not at module scope) because this
// file's worker process is not the same process that runs global-setup.ts,
// so DATABASE_URL is not guaranteed to already be in the environment.
let pool: Pool | undefined;
function getDb() {
  if (!pool) {
    loadDotenv({ path: [".env.local", ".env"] });
    if (!process.env.DATABASE_URL) {
      throw new Error("DATABASE_URL is not set; cannot clean up test rows.");
    }
    pool = new Pool({ connectionString: process.env.DATABASE_URL });
  }
  return drizzle(pool, { schema });
}

async function deleteCategoryByName(name: string): Promise<void> {
  await getDb()
    .delete(schema.categories)
    .where(eq(schema.categories.name, name));
}

async function deleteProgramByCourseId(courseId: string): Promise<void> {
  await getDb()
    .delete(schema.programs)
    .where(eq(schema.programs.courseId, courseId));
}

test.afterAll(async () => {
  await pool?.end();
});

test("admin dashboard", async ({ page }) => {
  await page.goto("/admin");
  await checkA11y(page);
});

test("admin inventory list", async ({ page }) => {
  await page.goto("/admin/inventory");
  await checkA11y(page);
});

test("admin inventory table interactions", async ({ page }) => {
  await page.goto("/admin/inventory");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await checkA11y(page);
  await closeMenu(page);
  await page.getByRole("button", { name: /Name/ }).click();
  await expect(
    page.getByRole("columnheader", { name: /Name/ })
  ).toHaveAttribute("aria-sort", /ascending|descending/);
  await checkA11y(page);
});

test("inventory new (staff)", async ({ page }) => {
  await page.goto("/inventory/new");
  await checkA11y(page);
});

test("inventory item detail (staff)", async ({ page }) => {
  await page.goto(`/inventory/${itemId}`);
  // Counterpart to the public suite's absence assertion: prove the staff
  // panel actually renders for a staff viewer rather than trusting the
  // conditional (a regression pinning viewerIsStaff to false would
  // otherwise still pass every a11y check).
  await expect(page.getByText("Staff panel")).not.toHaveCount(0);
  await checkA11y(page);
});

test("inventory item edit (staff)", async ({ page }) => {
  await page.goto(`/inventory/${itemId}/edit`);
  await checkA11y(page);
});

test("admin inventory requests", async ({ page }) => {
  await page.goto("/admin/inventory/requests");
  await checkA11y(page);
});

test("admin projects list", async ({ page }) => {
  await page.goto("/admin/projects");
  await checkA11y(page);
});

test("admin users list", async ({ page }) => {
  await page.goto("/admin/users");
  await checkA11y(page);
});

test("admin user detail", async ({ page }) => {
  await page.goto(`/admin/users/${userId}`);
  await checkA11y(page);
});

test("admin categories list", async ({ page }) => {
  await page.goto("/admin/categories");
  await checkA11y(page);
});

test("admin category detail", async ({ page }) => {
  await page.goto(`/admin/categories/${categoryId}`);
  await checkA11y(page);
});

test("admin programs list", async ({ page }) => {
  await page.goto("/admin/programs");
  await checkA11y(page);
});

test("admin program detail", async ({ page }) => {
  await page.goto(`/admin/programs/${programId}`);
  await checkA11y(page);
});

test("admin mentors list", async ({ page }) => {
  await page.goto("/admin/mentors");
  await checkA11y(page);
});

// The rest of this file exercises behavior that only a browser can prove:
// static SSR checks confirm markup is present or absent, but never actually
// click a sort header, toggle a column, resize the viewport, or scroll.

/**
 * Toggles a column's checkbox and waits for its columnheader to actually
 * appear before moving on. `onColumnVisibilityChange` derives its next state
 * from the current `hidden` prop, which only updates after the URL
 * round-trip commits, so firing the clicks back-to-back with nothing awaited
 * between them drops all but the last one. Confirming each toggle lands is
 * what a real user waiting to see the column would also, incidentally, do.
 */
async function toggleColumnOn(page: Page, label: string): Promise<void> {
  await page.getByRole("menuitemcheckbox", { name: label }).click();
  await expect(
    page.getByRole("columnheader", { name: label, exact: true })
  ).toBeVisible();
}

test("admin inventory table shows its default-hidden columns when toggled on", async ({
  page,
}) => {
  await page.goto("/admin/inventory");
  await waitForHydration(page);
  // Updated is not in this list: it is the page's default sort column and is
  // visible by default now, so toggling it here would hide it instead.
  const hiddenColumns = ["Label", "Serial", "Due", "Created"];

  await page.getByRole("button", { name: "Columns" }).click();
  for (const label of hiddenColumns) {
    await toggleColumnOn(page, label);
  }
  await closeMenu(page);

  for (const label of hiddenColumns) {
    await expect(
      page.getByRole("columnheader", { name: label, exact: true })
    ).toBeVisible();
    const cell = page.locator(`td[data-label="${label}"]`).first();
    await expect(cell).toBeVisible();
    const text = (await cell.textContent())?.trim() ?? "";
    // Every one of these columns' cell/accessorFn functions has never run in
    // any prior check (the SSR checks only ever saw the default column set).
    // A non-empty string proves the cell rendered rather than throwing.
    expect(text.length).toBeGreaterThan(0);
  }

  await checkA11y(page);
});

test("admin projects table shows its default-hidden columns when toggled on", async ({
  page,
}) => {
  await page.goto("/admin/projects");
  await waitForHydration(page);
  const hiddenColumns = ["Contact", "Teams", "Created", "Published"];

  await page.getByRole("button", { name: "Columns" }).click();
  for (const label of hiddenColumns) {
    await toggleColumnOn(page, label);
  }
  await closeMenu(page);

  for (const label of hiddenColumns) {
    await expect(
      page.getByRole("columnheader", { name: label, exact: true })
    ).toBeVisible();
    const cell = page.locator(`td[data-label="${label}"]`).first();
    await expect(cell).toBeVisible();
    const text = (await cell.textContent())?.trim() ?? "";
    expect(text.length).toBeGreaterThan(0);
  }

  await checkA11y(page);
});

test("sorting a column writes sort and dir into the URL", async ({ page }) => {
  await page.goto("/admin/inventory");
  await waitForHydration(page);
  const beforeRows = await page
    .locator(".admin-table tbody tr")
    .allTextContents();

  await page.getByRole("button", { name: "Category", exact: true }).click();

  // The URL and the rendered aria-sort must change together: this is the
  // same click producing both effects, not a URL update that happens to
  // coincide with a state change elsewhere. Which direction a fresh column
  // starts in is TanStack's call (it varies by column), so accept either:
  // the assertion is that a real toggle happened, not which one won.
  await expect(
    page.getByRole("columnheader", { name: "Category", exact: true })
  ).toHaveAttribute("aria-sort", /ascending|descending/);
  await expect(page).toHaveURL(/[?&]sort=category(&|$)/);
  await expect(page).toHaveURL(/[?&]dir=(asc|desc)(&|$)/);

  const afterRows = await page
    .locator(".admin-table tbody tr")
    .allTextContents();
  expect(afterRows).not.toEqual(beforeRows);
});

test("toggling a column writes cols into the URL, absent by default", async ({
  page,
}) => {
  await page.goto("/admin/inventory");
  await waitForHydration(page);
  // A fresh session with no stored preference: the param is genuinely absent,
  // not just not-yet-checked.
  await expect(page).not.toHaveURL(/[?&]cols=/);

  await page.getByRole("button", { name: "Columns" }).click();
  await page.getByRole("menuitemcheckbox", { name: "Location" }).click();
  await closeMenu(page);
  // The default-hidden columns (label, serial, dueAt, createdAt) stay hidden
  // too, so `cols` carries the whole hidden set, not a bare diff:
  // assert membership rather than an exact string. `toHaveURL` polls, which
  // matters here, since the URL update lands after an async navigation.
  // (Commas are URL-encoded as %2C, so a `\b` word-boundary check would break
  // on the trailing "C"; a plain substring match is what actually holds.)
  await expect(page).toHaveURL(/[?&]cols=[^&]*location/);
  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toHaveCount(0);

  // Toggling it back on returns the visible set to the page default: the
  // param must disappear again, not be written back with the literal default
  // list. This used to fail: resetColumns's sibling code path,
  // onColumnVisibilityChange, wrote the literal default set into storage
  // whenever a toggle happened to land back on the default, and
  // useSeedColumnsFromStorage would re-seed `cols` from that stored value on
  // the very next render, undoing the clean URL serializeHidden had just
  // produced. Fixed by clearing the stored preference instead of writing the
  // default into it (src/components/admin-data-table.tsx,
  // onColumnVisibilityChange and resetColumns both route through
  // clearStoredHidden now).
  await page.getByRole("button", { name: "Columns" }).click();
  await page.getByRole("menuitemcheckbox", { name: "Location" }).click();
  await closeMenu(page);
  await expect(page).not.toHaveURL(/[?&]cols=/);
  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toBeVisible();
});

test("column layout persists across a reload via the localStorage seed", async ({
  page,
}) => {
  await page.goto("/admin/inventory");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await page.getByRole("menuitemcheckbox", { name: "Location" }).click();
  await closeMenu(page);
  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toHaveCount(0);

  // A bare navigation (no cols param) is the actual test of the storage seed
  // path: page.reload() would keep the existing ?cols= in the URL and prove
  // nothing about localStorage. This simulates a fresh visit: a bookmark, a
  // new tab, or a browser restart, the kind only localStorage can inform.
  await page.goto("/admin/inventory");
  // Polls: the seed effect that reads localStorage and writes `cols` back
  // into the URL runs after hydration, not before this navigation resolves.
  await expect(page).toHaveURL(/[?&]cols=[^&]*location/);
  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toHaveCount(0);
});

test("Reset columns restores the default column set", async ({ page }) => {
  await page.goto("/admin/inventory");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await page.getByRole("menuitemcheckbox", { name: "Location" }).click();
  await closeMenu(page);
  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toHaveCount(0);
  await expect(page).toHaveURL(/[?&]cols=[^&]*location/);

  await page.getByRole("button", { name: "Columns" }).click();
  await page.getByRole("menuitem", { name: "Reset columns" }).click();

  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toBeVisible();
  // The URL comes back clean too: resetColumns clears the stored preference
  // rather than writing the default set into it, so there is nothing left
  // for useSeedColumnsFromStorage to re-seed from on this same render.
  await expect(page).not.toHaveURL(/[?&]cols=/);

  // Durability: a Reset has to survive a bare re-visit rather than being
  // silently undone by the stale preference it was supposed to replace.
  await page.goto("/admin/inventory");
  await expect(
    page.getByRole("columnheader", { name: "Location", exact: true })
  ).toBeVisible();
  await expect(page).not.toHaveURL(/[?&]cols=/);
});

test("admin table restacks into cards below 768px", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 800 });
  await page.goto("/admin/inventory");
  await waitForHydration(page);

  await expect(page.locator(".admin-table thead")).toBeHidden();

  const row = page.locator(".admin-table tbody tr").first();
  const cells = row.locator("td");
  const firstCell = cells.first();
  const secondCell = cells.nth(1);
  await expect(firstCell).toBeVisible();

  // Inventory's Name column is the card header: it titles the record, so it
  // spans the card and carries no field name. Anything else here would mean
  // the title is sharing its row with a redundant "Name" label.
  expect(await firstCell.getAttribute("data-card-header")).not.toBeNull();
  expect(await firstCell.getAttribute("data-label")).toBeNull();
  const headerBefore = await firstCell.evaluate(
    (el) => window.getComputedStyle(el, "::before").content
  );
  expect(headerBefore).toBe("none");

  // Full horizontal space: the header cell is as wide as the card itself.
  const rowBox = await row.boundingBox();
  const headerBox = await firstCell.boundingBox();
  if (!(rowBox && headerBox)) {
    throw new Error("Row or header cell not found for the width check.");
  }
  expect(headerBox.width).toBeGreaterThan(rowBox.width * 0.9);

  // Every other field still gets its name from a CSS
  // `content: attr(data-label)` pseudo-element, which is invisible to
  // getByText. Read the resolved pseudo-element content directly, which
  // fails if the attribute is missing, empty, or the CSS selector stops
  // matching.
  const dataLabel = await secondCell.getAttribute("data-label");
  expect(dataLabel).toBeTruthy();
  const beforeContent = await secondCell.evaluate(
    (el) => window.getComputedStyle(el, "::before").content
  );
  expect(beforeContent).toBe(`"${dataLabel}"`);

  // The label check alone would still pass if the row stayed in table layout
  // (cells side by side) rather than actually restacking into a card. Two
  // cells of the same row sitting side by side share a y; stacked, the
  // second sits below the first.
  const firstBox = await firstCell.boundingBox();
  const secondBox = await secondCell.boundingBox();
  if (!(firstBox && secondBox)) {
    throw new Error("Row cells not found for the stacking check.");
  }
  expect(secondBox.y).toBeGreaterThan(firstBox.y);
});

test("admin table header stays pinned while the body scrolls at md and up", async ({
  page,
}) => {
  // Short enough that calc(100vh - 14rem) forces the wrapper to scroll even
  // with the handful of rows the dev seed provides, and wide enough (>=768px)
  // to stay off the mobile-card layout.
  await page.setViewportSize({ width: 1024, height: 420 });
  await page.goto("/admin/inventory");
  await waitForHydration(page);

  const container = page.locator('[data-slot="table-container"]');
  const header = page.getByRole("columnheader", { name: "Name", exact: true });
  const firstRowCell = page
    .locator(".admin-table tbody tr")
    .first()
    .locator("td")
    .first();

  const scrollHeight = await container.evaluate((el) => el.scrollHeight);
  const clientHeight = await container.evaluate((el) => el.clientHeight);
  // Positive control: the container must actually overflow, or scrolling it
  // below would be a no-op and every assertion after this would be vacuous.
  expect(scrollHeight).toBeGreaterThan(clientHeight);

  const containerBox = await container.boundingBox();
  if (!containerBox) {
    throw new Error("Table container not found.");
  }
  const rowBoxBefore = await firstRowCell.boundingBox();
  if (!rowBoxBefore) {
    throw new Error("First row not found before scrolling.");
  }
  // Second positive control: before scrolling, the first data row renders
  // below the header, not already hidden behind it.
  expect(rowBoxBefore.y).toBeGreaterThan(containerBox.y);

  await container.evaluate((el) => {
    el.scrollTop = el.scrollHeight;
  });

  const scrollTop = await container.evaluate((el) => el.scrollTop);
  expect(scrollTop).toBeGreaterThan(0);

  // `position: sticky` only pins once the element would otherwise scroll
  // past its container's edge, so a bare "same position as before scrolling"
  // check is wrong here, since the header's natural (unstuck) position and
  // its pinned position aren't the same point. The real test is that once
  // scrolled, it holds flush with the scroll container's own top edge, the
  // definition of "pinned," rather than being carried off with the content.
  await expect(header).toBeVisible();
  const headerBoxAfter = await header.boundingBox();
  if (!headerBoxAfter) {
    throw new Error("Header column not found after scrolling.");
  }
  // `top: 0` pins to the scroll container's padding box, while boundingBox
  // reports its border box, so the container's own top border sits between
  // them. Add it rather than loosening this to a tolerance: the point of the
  // assertion is that the header is exactly flush, not approximately.
  const containerBorderTop = await container.evaluate(
    (el) => Number.parseFloat(window.getComputedStyle(el).borderTopWidth) || 0
  );
  expect(Math.round(headerBoxAfter.y)).toBe(
    Math.round(containerBox.y + containerBorderTop)
  );

  // The row that was below the header has now scrolled up behind it,
  // confirming body content actually moved underneath a header that held its
  // position, rather than both having simply stayed still.
  const rowBoxAfter = await firstRowCell.boundingBox();
  if (!rowBoxAfter) {
    throw new Error("First row not found after scrolling.");
  }
  expect(rowBoxAfter.y).toBeLessThan(headerBoxAfter.y);
});

// The three tables migrated in tasks 9-11 get the same interaction pass
// task 8 gave inventory: open the Columns menu, scan, activate a sort
// header, confirm aria-sort actually changed, scan again.

test("admin categories table interactions", async ({ page }) => {
  await page.goto("/admin/categories");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await checkA11y(page);
  await closeMenu(page);
  // Not "Type": that's this page's default sort column (see DEFAULT_SORT in
  // the route), so its header already carries aria-sort="ascending" before
  // any click, which would make the assertion below pass even if the click
  // silently no-oped. "Name" starts unsorted, so a passing assertion here
  // can only mean the click actually did something. Capturing the before
  // state and asserting a change closes the same hole permanently, in case
  // a future default-sort change ever put a table back in this position.
  const header = page.getByRole("columnheader", { name: "Name", exact: true });
  const before = await header.getAttribute("aria-sort");
  await page.getByRole("button", { name: "Name", exact: true }).click();
  await expect(header).toHaveAttribute("aria-sort", /ascending|descending/);
  expect(await header.getAttribute("aria-sort")).not.toBe(before);
  await checkA11y(page);
});

test("admin programs table interactions", async ({ page }) => {
  await page.goto("/admin/programs");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await checkA11y(page);
  await closeMenu(page);
  const header = page.getByRole("columnheader", {
    exact: true,
    name: "Course name",
  });
  const before = await header.getAttribute("aria-sort");
  await page.getByRole("button", { name: "Course name", exact: true }).click();
  await expect(header).toHaveAttribute("aria-sort", /ascending|descending/);
  expect(await header.getAttribute("aria-sort")).not.toBe(before);
  await checkA11y(page);
});

test("admin users table interactions", async ({ page }) => {
  await page.goto("/admin/users");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await checkA11y(page);
  await closeMenu(page);
  const header = page.getByRole("columnheader", { exact: true, name: "Email" });
  const before = await header.getAttribute("aria-sort");
  await page.getByRole("button", { name: "Email", exact: true }).click();
  await expect(header).toHaveAttribute("aria-sort", /ascending|descending/);
  expect(await header.getAttribute("aria-sort")).not.toBe(before);
  await checkA11y(page);
});

// /admin/users is the only table that paginates and orders on the server
// (serverSorted), so a header click there means something none of the
// client-sorted tables can prove: that the rows themselves came back from a
// new request, not a browser-side re-sort of what was already on screen.

test("admin users table sort header activates via keyboard", async ({
  page,
}) => {
  await page.goto("/admin/users");
  await waitForHydration(page);
  const columnHeader = page.getByRole("columnheader", {
    exact: true,
    name: "Name",
  });
  const before = await columnHeader.getAttribute("aria-sort");
  const header = page.getByRole("button", { name: "Name", exact: true });
  await header.focus();
  await expect(header).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(columnHeader).toHaveAttribute(
    "aria-sort",
    /ascending|descending/
  );
  expect(await columnHeader.getAttribute("aria-sort")).not.toBe(before);
});

test("admin users list: sorting a column reorders the rendered rows, not just the URL", async ({
  page,
}) => {
  await page.goto("/admin/users");
  await waitForHydration(page);
  const header = page.getByRole("columnheader", {
    exact: true,
    name: "Email",
  });
  const beforeSort = await header.getAttribute("aria-sort");
  const beforeRows = await page
    .locator(".admin-table tbody tr")
    .allTextContents();
  // Positive control: an empty "before" snapshot would make the inequality
  // below pass for the wrong reason.
  expect(beforeRows.length).toBeGreaterThan(0);

  await page.getByRole("button", { name: "Email", exact: true }).click();
  await expect(header).toHaveAttribute("aria-sort", /ascending|descending/);
  expect(await header.getAttribute("aria-sort")).not.toBe(beforeSort);
  await expect(page).toHaveURL(/[?&]sort=email(&|$)/);
  await expect(page).toHaveURL(/[?&]dir=(asc|desc)(&|$)/);

  // sort/dir are in this route's loaderDeps, so the header click above sent
  // a new request and the loader returned a (possibly) different page,
  // which is what the row comparison below actually tests. That is not the
  // same claim as "serverSorted/manualSorting is wired correctly": resorting
  // an already server-ordered set of unique rows client-side is a no-op, so
  // this test would still pass even if that prop were broken. serverSorted
  // itself is covered by the admin-data-table unit tests, not here.
  const afterRows = await page
    .locator(".admin-table tbody tr")
    .allTextContents();
  expect(afterRows).not.toEqual(beforeRows);
});

test("admin users list: sorting from page 2 returns to page 1", async ({
  page,
}) => {
  await page.goto("/admin/users?page=2");
  await waitForHydration(page);
  // Positive control: page 2 has to hold real rows, from the pagination
  // fixtures global-setup.ts creates, or the sort header below would not be
  // in the DOM (AdminDataTable renders its empty state instead of a table
  // once rows.length is 0) and the click after this would throw rather than
  // prove anything about the page reset. Requiring totalPages >= 2 (not just
  // \d+) matters here: "Page 2 of 1" would satisfy a bare \d+ pattern too,
  // which is exactly the broken-fixture case this control exists to catch.
  await expect(page.getByText(/^Page 2 of [2-9]\d*$/)).toBeVisible();

  await page.getByRole("button", { name: "Email", exact: true }).click();

  await expect(page.getByText(/^Page 1 of \d+$/)).toBeVisible();
  await expect(page).not.toHaveURL(/[?&]page=2(&|$)/);
});

// /admin/categories and /admin/programs are the first routes on this branch
// to put a Radix Dialog (the create form) and AdminDataTable's Radix
// DropdownMenu (Columns) on the same page. AdminDataTable sets modal={false}
// on its dropdown specifically to avoid leaving the rest of the page under
// aria-hidden while it's open; nothing before this had a second overlay on
// the same page to prove that choice still holds up. Both assertions below
// exist because of that: the dialog closing has to actually clear whatever
// it hid, and the dropdown has to still work afterward.

test("admin programs: create dialog and Columns dropdown coexist", async ({
  page,
}) => {
  await page.goto("/admin/programs");
  await waitForHydration(page);

  const unique = Date.now();
  const courseId = `A11Y-DLG-${unique}`;
  const courseName = `A11y Dialog Program ${unique}`;

  try {
    await page.getByRole("button", { name: "+ New program" }).click();
    const dialog = page.getByRole("dialog", { name: "New program" });
    await dialog.getByLabel("Course ID").fill(courseId);
    await dialog.getByLabel("Course name").fill(courseName);
    await dialog.getByRole("button", { name: "Create program" }).click();

    // Radix keeps DialogContent mounted through its animate-out transition,
    // and the aria-hidden it puts on the rest of the page while open comes
    // off at unmount, not at the moment `open` flips to false. Wait for it
    // to actually leave the DOM before scanning, the same reason closeMenu
    // waits out the dropdown's own animate-out rather than trusting Escape
    // alone.
    await expect(page.getByRole("dialog")).toHaveCount(0);
    // onCreate calls router.invalidate() on success: the new row appearing
    // is proof the create round-tripped and the loader re-ran, not just that
    // the dialog closed.
    await expect(
      page.getByRole("cell", { name: courseId, exact: true })
    ).toBeVisible();

    await checkA11y(page);

    // With the dialog fully closed, the Columns dropdown still opens and
    // toggles a column: not blocked or left inert by whatever the dialog's
    // own teardown did to the rest of the page.
    await page.getByRole("button", { name: "Columns" }).click();
    await toggleColumnOn(page, "Description");
    await closeMenu(page);
    await checkA11y(page);
  } finally {
    await deleteProgramByCourseId(courseId);
  }
});

test("admin categories: create dialog and Columns dropdown coexist", async ({
  page,
}) => {
  await page.goto("/admin/categories");
  await waitForHydration(page);

  const uniqueName = `A11y Dialog Category ${Date.now()}`;

  try {
    await page.getByRole("button", { name: "+ New category" }).click();
    const dialog = page.getByRole("dialog", { name: "New project category" });
    await dialog.getByLabel("Name").fill(uniqueName);
    // The Type field's accessible name is ambiguous between its <label> text
    // ("Type") and its own visible content ("Select or create a type"), so
    // it is targeted by id rather than by role name here.
    await dialog.locator("#cat-type").click();
    // "technology" is guaranteed to exist as a type: global-setup.ts's
    // a11y-test-category fixture uses it, and listCategoryTypes reads types
    // from existing categories, so it's always in this popover's list.
    await page.getByRole("option", { name: "technology", exact: true }).click();
    await dialog.getByRole("button", { name: "Create category" }).click();

    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(
      page.getByRole("cell", { name: uniqueName, exact: true })
    ).toBeVisible();

    await checkA11y(page);

    await page.getByRole("button", { name: "Columns" }).click();
    await toggleColumnOn(page, "Created");
    await closeMenu(page);
    await checkA11y(page);
  } finally {
    await deleteCategoryByName(uniqueName);
  }
});
