import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import {
  closeMenu,
  expectNoHorizontalOverflow,
  toggleColumnOn,
  waitForHydration,
  waitForSurfaceSettled,
} from "../shared/playwright";
import { checkA11y, expectUnderlinedAtRest } from "./helpers";

// .fixtures.json is generated by global-setup.ts: run `npm run test:accessibility` to populate it.
const { projectId, itemId } = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), ".fixtures.json"),
    "utf-8"
  )
) as { projectId: string; itemId: string };

// Two panels named after the header nav, each carrying its links, and the
// proposal statuses in order under them. Nothing on the page looks pressable
// without being a link (#393), and the panels stack at a phone width.
test("@smoke home page", async ({ page }) => {
  await page.goto("/");
  await expect(
    page.getByRole("link", { name: "Browse the catalog" })
  ).toHaveAttribute("href", "/projects");
  await expect(
    page.getByRole("link", { name: "Propose a project" })
  ).toHaveAttribute("href", "/projects/new");
  await expect(
    page.getByRole("link", { name: "See what you can borrow" })
  ).toHaveAttribute("href", "/inventory");
  await expect(page.getByRole("heading", { level: 3 })).toHaveText([
    "Draft",
    "Submitted",
    "Changes requested",
    "Approved",
    "Published",
  ]);
  await checkA11y(page);

  await page.setViewportSize({ width: 375, height: 812 });
  await expect(
    page.getByRole("link", { name: "Propose a project" })
  ).toBeVisible();
  await expect(
    page.getByRole("link", { name: "See what you can borrow" })
  ).toBeVisible();
  await expectNoHorizontalOverflow(page);
  await checkA11y(page);
});

test("@smoke sign-in page", async ({ page }) => {
  await page.goto("/sign-in");
  // The page-level privacy notice is a link in muted running text (#586).
  await expectUnderlinedAtRest(
    page.getByRole("link", { name: "privacy policy", exact: true })
  );
  await checkA11y(page);
});

/**
 * A save that fails announces, through `FieldError` (#411).
 *
 * Sign-in is the form a test can fail on demand without a fixture: a wrong
 * code, a real refusal from the server, and the message that comes back has to
 * reach a screen reader. Before `FieldError` carried `role="alert"`, all but
 * two of about forty of these paragraphs rendered silently, and the component
 * test can only prove the role is on the element; this proves a real failed
 * submit puts a real message inside it. The address needs no account: asking
 * for a code answers the same either way, and a wrong one is refused either
 * way.
 */
test("@smoke a failed sign-in announces its error", async ({ page }) => {
  await page.goto("/sign-in");
  await waitForHydration(page, "form");
  await expect(page.getByRole("alert")).toHaveCount(0);

  await page.getByLabel("Email", { exact: true }).fill("nobody@example.com");
  await page.getByRole("button", { name: "Email me a code" }).click();
  await page.getByLabel("Code", { exact: true }).fill("000000");
  await page.getByRole("button", { name: "Confirm code" }).click();

  const alert = page.getByRole("alert");
  await expect(alert).toBeVisible();
  await expect(alert).not.toBeEmpty();
  await expect(page).toHaveURL(/\/sign-in/);
  await checkA11y(page);
});

// The banner carries the office address as a link inside `role="alert"`, so
// the refusal and the one thing the reader can do about it are announced
// together. An unknown code lands on the fallback, which is what a new Better
// Auth error code would produce.
for (const code of ["user_info_is_missing", "not_a_known_code"]) {
  test(`@smoke sign-in page, ONID refusal ${code}`, async ({ page }) => {
    await page.goto(`/sign-in?error=${code}`);
    const alert = page.getByRole("alert");
    await expect(alert).toBeVisible();
    const link = alert.getByRole("link", { name: /@/ });
    await expect(link).toHaveAttribute("href", /^mailto:/);
    await expectUnderlinedAtRest(link);
    await link.focus();
    await expect(link).toBeFocused();
    await checkA11y(page);
  });
}

/**
 * The emailed code form, past its first step (#576).
 *
 * The page scan sees only the address step, because the later ones are behind
 * a real send. The code step therefore reaches no clean scan unless one drives
 * it, and it is the one most likely to go wrong: it is the only one-time-code
 * field in the app, drawn as six slots over one real input (#600), and a wrong
 * code marks every slot `aria-invalid`. Both states are scanned.
 *
 * The name step is scanned in the same test rather than its own, because each
 * test is a real send to one address in light and dark alike, and that address
 * has a per-recipient mail budget (ADR-0046). It carries the privacy notice's
 * link (#586). This suite has no mail log to read a code from, so the check is
 * answered the way the server answers a right code for an address with no
 * account; the form acts on the error code, which is all the stub has to match.
 */
test("@smoke sign-in page, the emailed code form", async ({ page }) => {
  await page.goto("/sign-in");
  await waitForHydration(page, "form");

  await page.getByLabel("Email", { exact: true }).fill("nobody@example.com");
  await page.getByRole("button", { name: "Email me a code" }).click();

  await expect(page.getByLabel("Code", { exact: true })).toBeVisible();
  await checkA11y(page);

  const check = "**/api/auth/email-otp/check-verification-otp";
  await page.route(check, (route) =>
    route.fulfill({
      status: 400,
      contentType: "application/json",
      body: JSON.stringify({ code: "INVALID_OTP", message: "Invalid OTP" }),
    })
  );
  await page.getByLabel("Code", { exact: true }).fill("000000");
  await page.getByRole("button", { name: "Confirm code" }).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await checkA11y(page);
  await page.unroute(check);

  await page.route(check, (route) =>
    route.fulfill({
      status: 400,
      contentType: "application/json",
      body: JSON.stringify({
        code: "USER_NOT_FOUND",
        message: "User not found",
      }),
    })
  );
  await page.getByLabel("Code", { exact: true }).fill("123456");
  await page.getByRole("button", { name: "Confirm code" }).click();

  await expect(page.getByLabel("Your name", { exact: true })).toBeVisible();
  await expectUnderlinedAtRest(
    page
      .locator("form")
      .getByRole("link", { name: "privacy policy", exact: true })
  );
  await checkA11y(page);
});

test("@smoke privacy page", async ({ page }) => {
  await page.goto("/privacy");
  await checkA11y(page);
});

test("@smoke projects list", async ({ page }) => {
  await page.goto("/projects");
  await waitForHydration(page);
  // Signed out: the proposal door stays hidden, like the bookmarks count.
  await expect(page.getByRole("link", { name: "Propose project" })).toHaveCount(
    0
  );
  // The sign-in prompt under the search is a link inside muted prose (#361).
  await expectUnderlinedAtRest(
    page.getByRole("link", { name: "Sign in to get recommendations" })
  );
  // The fields and the syntax are on the hint line under the row, and the
  // searchbox is described by it; the placeholder is only a name (#369).
  await expect(
    page.getByRole("searchbox", { name: "Search projects" })
  ).toHaveAccessibleDescription(/Quote a "phrase"/);
  await checkA11y(page);
});

test("@smoke projects list, paginated", async ({ page }) => {
  await page.goto("/projects");
  await waitForHydration(page);

  const pager = page.getByRole("navigation", { name: "Pagination" });
  await expect(pager).toBeVisible();

  // The seeded catalog fits on one page, so both controls are disabled here.
  // pointer-events-none used to leave a disabled control focusable and
  // activatable, which no axe rule reports: it must be out of the tab order
  // entirely, not just unclickable with a mouse.
  for (const label of ["Previous", "Next"]) {
    const control = pager.getByText(label);
    await expect(control).toHaveAttribute("aria-disabled", "true");
    await expect(control).toHaveAttribute("tabindex", "-1");
  }
  await checkA11y(page);
});

test("@smoke projects list, filters aside at xl", async ({ page }) => {
  // The suite runs at 1280, which is where the aside appears (#350): the
  // program select and the switches are in it, and the Filters button that
  // opens the sheet is gone.
  await page.goto("/projects");
  await waitForHydration(page);
  const aside = page.getByRole("complementary", { name: "Filters" });
  await expect(aside.getByRole("combobox", { name: "Program" })).toBeVisible();
  // The archive mode is a radio above the switches, and the accepting
  // switch carries its hint as its description (#383). That switch is the
  // one that opens on (#419), so its hint says what turning it off does.
  await expect(aside.getByRole("radiogroup", { name: "Show" })).toBeVisible();
  await expect(
    aside.getByRole("radio", { name: "Current projects" })
  ).toBeChecked();
  const archived = aside.getByRole("radio", { name: "Archived projects" });
  await expect(archived).toBeVisible();
  const accepting = aside.getByRole("switch", {
    name: "are looking for team members",
  });
  await expect(accepting).toBeVisible();
  await expect(accepting).toBeChecked();
  await expect(accepting).toHaveAccessibleDescription(
    "Turn off to also show projects whose team is full."
  );
  await expect(page.getByRole("button", { name: "Filters" })).toBeHidden();
  await checkA11y(page);
  // Picking Archived lands on the same param a pasted link carries.
  await archived.click();
  await expect(page).toHaveURL(/archivedOnly=true/);
  await expect(archived).toBeChecked();
  await expect(
    aside.getByRole("radio", { name: "Current projects" })
  ).not.toBeChecked();
});

test("@smoke projects list, filters sheet at 375px", async ({ page }) => {
  // Below xl the same form opens in a left sheet; a change made there keeps
  // the sheet open, since it is a navigation on the same route.
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto("/projects");
  await waitForHydration(page);
  await expect(
    page.getByRole("complementary", { name: "Filters" })
  ).toBeHidden();
  await page.getByRole("button", { name: "Filters" }).click();
  const sheet = page.getByRole("dialog", { name: "Filters" });
  const accepting = sheet.getByRole("switch", {
    name: "are looking for team members",
  });
  await expect(accepting).toBeVisible();
  // Focus lands inside the sheet on open, and the page under it does not
  // grow sideways for the overlay.
  await expect(sheet.locator(":focus")).toHaveCount(1);
  await expectNoHorizontalOverflow(page);
  await checkA11y(page);
  // Off, not on: this switch opens checked (#419), so the click that moves it
  // away from its default is the one the Filters badge counts below.
  await accepting.click();
  await expect(page).toHaveURL(/acceptingOnly=false/);
  await expect(sheet).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(sheet).toBeHidden();
  // Focus returns to the button, which now carries the count of what was
  // changed. Tab from the search reaches it with nothing in between: the
  // recommendation prompt renders under the row, not inside it. Four
  // stops: the sort, the two view toggle buttons, the Filters button.
  const button = page.getByRole("button", { name: "Filters 1" });
  await expect(button).toBeFocused();
  await page.getByRole("searchbox", { name: "Search projects" }).focus();
  for (let i = 0; i < 4; i += 1) {
    await page.keyboard.press("Tab");
  }
  await expect(button).toBeFocused();
  // Enter opens it from the keyboard, and Clear all (a link-variant Button,
  // visible now that a filter is on) is what the dark scan measures.
  await page.keyboard.press("Enter");
  await expect(sheet).toBeVisible();
  await expect(sheet.getByRole("button", { name: "Clear all" })).toBeVisible();
  await checkA11y(page);
  await page.keyboard.press("Escape");
  await expect(sheet).toBeHidden();
});

test("@smoke projects list, table mode", async ({ page }) => {
  await page.goto("/projects?view=table");
  await expect(page.locator(".admin-table")).toBeVisible();
  await checkA11y(page);
});

test("projects list: the view toggle writes the mode into the URL and storage", async ({
  page,
}) => {
  await page.goto("/projects");
  await waitForHydration(page);
  // A fresh session with nothing stored: the param is genuinely absent.
  await expect(page).not.toHaveURL(/[?&]view=/);

  await page.getByRole("button", { name: "Table view" }).click();
  await expect(page).toHaveURL(/[?&]view=table(&|$)/);
  await expect(page.locator(".admin-table")).toBeVisible();
  await checkA11y(page);

  await page.getByRole("button", { name: "Card view" }).click();
  await expect(page).toHaveURL(/[?&]view=card(&|$)/);
  await expect(page.locator(".admin-table")).toHaveCount(0);

  // A bare navigation (no view param) is the actual test of the storage
  // seed: page.reload() would keep ?view= in the URL and prove nothing about
  // localStorage. Polls, because the seed effect runs after hydration.
  await page.getByRole("button", { name: "Table view" }).click();
  await expect(page).toHaveURL(/[?&]view=table(&|$)/);
  await page.goto("/projects");
  await expect(page).toHaveURL(/[?&]view=table(&|$)/);
  await expect(page.locator(".admin-table")).toBeVisible();
});

test("projects table interactions", async ({ page }) => {
  await page.goto("/projects?view=table");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await waitForSurfaceSettled(page.getByRole("menu"));
  await checkA11y(page);
  await closeMenu(page);

  // The headers stopped sorting in #475, so what used to be asserted here
  // (a click writing ?sort= and ?dir=) is now asserted not to exist. Every
  // header, not just Title: one column left sortable would put a second
  // ordering back on the page beside the Sort select.
  const headers = page.getByRole("columnheader");
  const count = await headers.count();
  expect(count).toBeGreaterThan(0);
  for (let i = 0; i < count; i++) {
    const header = headers.nth(i);
    await expect(header).not.toHaveAttribute("aria-sort", /.*/);
    await expect(header.getByRole("button")).toHaveCount(0);
  }
  await checkA11y(page);
});

test("projects listing keeps one ordering in both views", async ({ page }) => {
  // The criterion #475 exists for: the same URL renders the same rows in the
  // same order whichever view it is in, which was false while the table
  // applied its own `updatedAt desc` on top of the server's order.
  const url = "/projects?order=title&acceptingOnly=false";
  await page.goto(`${url}&view=table`);
  await waitForHydration(page);
  const tableTitles = await page
    .locator("tbody tr td:first-child a")
    .allInnerTexts();

  await page.goto(`${url}&view=card`);
  await waitForHydration(page);
  // `h3` because that is what ProjectCard puts the title in, and it is the
  // only heading level inside a card.
  const cardTitles = await page
    .getByRole("heading", { level: 3 })
    .allInnerTexts();

  expect(tableTitles.length).toBeGreaterThan(0);
  expect(cardTitles.map((t) => t.trim())).toEqual(
    tableTitles.map((t) => t.trim())
  );
});

test("projects table shows its default-hidden columns when toggled on", async ({
  page,
}) => {
  await page.goto("/projects?view=table");
  await waitForHydration(page);
  const hiddenColumns = [
    "Description",
    "Problem statement",
    "Objectives",
    "Min qualifications",
    "Pref qualifications",
    "License restrictions",
    "URL",
  ];

  await page.getByRole("button", { name: "Columns" }).click();
  for (const label of hiddenColumns) {
    await toggleColumnOn(page, label);
  }
  await closeMenu(page);

  for (const label of hiddenColumns) {
    await expect(
      page.getByRole("columnheader", { name: label, exact: true })
    ).toBeVisible();
    const cell = page.locator(`td[data-label="${label}"]`).first();
    await expect(cell).toBeVisible();
    // A dash for an empty field still counts: the point is that the cell
    // rendered rather than threw, since nothing before this ever ran these
    // columns' cell functions.
    const text = (await cell.textContent())?.trim() ?? "";
    expect(text.length).toBeGreaterThan(0);
  }

  await checkA11y(page);
});

test("@smoke project detail", async ({ page }) => {
  await page.goto(`/projects/${projectId}`);
  // The contact address and the URL sit in body copy (#364); global-setup
  // gives the fixture both.
  await expectUnderlinedAtRest(
    page.getByRole("link", { name: /^a11y-contact@/ })
  );
  await expectUnderlinedAtRest(
    page.getByRole("link", { name: "https://example.com/a11y-project" })
  );
  await checkA11y(page);
});

test("@smoke inventory list", async ({ page }) => {
  await page.goto("/inventory");
  await checkA11y(page);
  await expect(
    page.getByRole("searchbox", { name: "Search inventory" })
  ).toHaveAccessibleDescription(/Quote a "phrase"/);
});

test("@smoke inventory list, filters aside at xl", async ({ page }) => {
  await page.goto("/inventory");
  await waitForHydration(page);
  const aside = page.getByRole("complementary", { name: "Filters" });
  await expect(aside.getByRole("combobox", { name: "Status" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Filters" })).toBeHidden();
  await checkA11y(page);
});

test("@smoke inventory list, filters sheet at 375px", async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto("/inventory");
  await waitForHydration(page);
  await expect(
    page.getByRole("complementary", { name: "Filters" })
  ).toBeHidden();
  await page.getByRole("button", { name: "Filters" }).click();
  const sheet = page.getByRole("dialog", { name: "Filters" });
  await expect(sheet.getByRole("combobox", { name: "Status" })).toBeVisible();
  await expect(sheet.locator(":focus")).toHaveCount(1);
  await expectNoHorizontalOverflow(page);
  await checkA11y(page);
  await page.keyboard.press("Escape");
  await expect(sheet).toBeHidden();
  await expect(page.getByRole("button", { name: "Filters" })).toBeFocused();
});

test("@smoke inventory list, table mode", async ({ page }) => {
  await page.goto("/inventory?view=table");
  await expect(page.locator(".admin-table")).toBeVisible();
  await checkA11y(page);
});

test("inventory list: the view toggle writes the mode into the URL", async ({
  page,
}) => {
  await page.goto("/inventory");
  await waitForHydration(page);
  await expect(page).not.toHaveURL(/[?&]view=/);
  await page.getByRole("button", { name: "Table view" }).click();
  await expect(page).toHaveURL(/[?&]view=table(&|$)/);
  await expect(page.locator(".admin-table")).toBeVisible();
  await page.getByRole("button", { name: "Card view" }).click();
  await expect(page).toHaveURL(/[?&]view=card(&|$)/);
  await expect(page.locator(".admin-table")).toHaveCount(0);

  // One stored preference for both listings: a bare revisit of /inventory is
  // seeded from what the toggle on either page last wrote.
  await page.getByRole("button", { name: "Table view" }).click();
  await expect(page).toHaveURL(/[?&]view=table(&|$)/);
  await page.goto("/inventory");
  await expect(page).toHaveURL(/[?&]view=table(&|$)/);
  await expect(page.locator(".admin-table")).toBeVisible();
});

test("inventory table interactions", async ({ page }) => {
  await page.goto("/inventory?view=table");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await waitForSurfaceSettled(page.getByRole("menu"));
  await checkA11y(page);
  await closeMenu(page);

  // The headers stopped sorting in #477, as /projects' did in #475: a header
  // click used to write ?sort=status and reorder only the twenty rows on
  // screen. Every header, so one left sortable fails here.
  const headers = page.getByRole("columnheader");
  const count = await headers.count();
  expect(count).toBeGreaterThan(0);
  for (let i = 0; i < count; i++) {
    const header = headers.nth(i);
    await expect(header).not.toHaveAttribute("aria-sort", /.*/);
    await expect(header.getByRole("button")).toHaveCount(0);
  }

  // The Sort select is the one ordering: it reads the default before any
  // choice, and a choice goes to the server through the URL, back on page 1.
  const sort = page.getByRole("combobox", { name: "Sort" });
  await expect(sort).toHaveText("Available first");
  // Not scanned open: Radix Select hides the rest of the page with
  // aria-hidden while its listbox is up, which axe reports as
  // aria-hidden-focus on every focusable thing behind it. No Select in this
  // suite is scanned open, /projects' Sort select included.
  await sort.click();
  await page.getByRole("option", { name: "Name A-Z" }).click();
  await expect(page).toHaveURL(/[?&]order=name(&|$)/);
  await expect(page).toHaveURL(/[?&]page=1(&|$)/);
  await expect(sort).toHaveText("Name A-Z");
  await checkA11y(page);
});

test("inventory listing keeps one ordering in both views", async ({ page }) => {
  // The same URL renders the same items in the same order in either view.
  // Two orderings, because the table's old page-local default was Name A-Z:
  // under that one alone, a table still sorting on its own would pass by
  // agreeing with the server.
  for (const order of ["name", "updated"]) {
    await page.goto(`/inventory?order=${order}&view=table`);
    await waitForHydration(page);
    const tableNames = await page
      .locator("tbody tr td:first-child a")
      .allInnerTexts();

    await page.goto(`/inventory?order=${order}&view=card`);
    await waitForHydration(page);
    // `h3` because that is where InventoryCard puts the name.
    const cardNames = await page
      .getByRole("heading", { level: 3 })
      .allInnerTexts();

    expect(tableNames.length, order).toBeGreaterThan(0);
    expect(
      cardNames.map((n) => n.trim()),
      order
    ).toEqual(tableNames.map((n) => n.trim()));
  }
});

test("inventory table shows its description column when toggled on", async ({
  page,
}) => {
  await page.goto("/inventory?view=table");
  await waitForHydration(page);
  await page.getByRole("button", { name: "Columns" }).click();
  await toggleColumnOn(page, "Description");
  await closeMenu(page);
  const cell = page.locator('td[data-label="Description"]').first();
  await expect(cell).toBeVisible();
  expect(((await cell.textContent()) ?? "").trim().length).toBeGreaterThan(0);
  await checkA11y(page);
});

test("@smoke inventory item detail", async ({ page }) => {
  await page.goto(`/inventory/${itemId}`);
  // One page now serves both audiences, so prove the staff half is absent
  // for an anonymous viewer rather than trusting the conditional.
  await expect(page.getByText("Staff panel")).toHaveCount(0);
  await checkA11y(page);
});

test("the traffic reports send a signed-out visitor to sign in", async ({
  page,
}) => {
  await page.goto("/admin/traffic");
  await page.waitForURL((url) => url.pathname === "/sign-in");
});
