import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import { waitForHydration } from "../shared/playwright";
import { checkA11y } from "./helpers";

// .fixtures.json is generated by global-setup.ts: run `npm run test:accessibility` to populate it.
const { projectId, itemId } = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), ".fixtures.json"),
    "utf-8"
  )
) as { projectId: string; itemId: string };

test("@smoke home page", async ({ page }) => {
  await page.goto("/");
  await checkA11y(page);
});

test("@smoke sign-in page", async ({ page }) => {
  await page.goto("/sign-in");
  await checkA11y(page);
});

test("@smoke sign-up page", async ({ page }) => {
  await page.goto("/sign-up");
  await checkA11y(page);
});

test("@smoke privacy page", async ({ page }) => {
  await page.goto("/privacy");
  await checkA11y(page);
});

test("@smoke verify-email page", async ({ page }) => {
  await page.goto("/verify-email");
  await checkA11y(page);
});

test("@smoke forgot-password page", async ({ page }) => {
  await page.goto("/forgot-password");
  await checkA11y(page);
});

test("@smoke reset-password page", async ({ page }) => {
  await page.goto("/reset-password?token=a11y-test-token");
  await checkA11y(page);
});

test("@smoke projects list", async ({ page }) => {
  await page.goto("/projects");
  await checkA11y(page);
});

test("@smoke projects list, paginated", async ({ page }) => {
  await page.goto("/projects");
  await waitForHydration(page);

  const pager = page.getByRole("navigation", { name: "Pagination" });
  await expect(pager).toBeVisible();

  // The seeded catalog fits on one page, so both controls are disabled here.
  // pointer-events-none used to leave a disabled control focusable and
  // activatable, which no axe rule reports: it must be out of the tab order
  // entirely, not just unclickable with a mouse.
  for (const label of ["Previous", "Next"]) {
    const control = pager.getByText(label);
    await expect(control).toHaveAttribute("aria-disabled", "true");
    await expect(control).toHaveAttribute("tabindex", "-1");
  }
  await checkA11y(page);
});

test("@smoke project detail", async ({ page }) => {
  await page.goto(`/projects/${projectId}`);
  await checkA11y(page);
});

test("@smoke inventory list", async ({ page }) => {
  await page.goto("/inventory");
  await checkA11y(page);
});

test("@smoke inventory item detail", async ({ page }) => {
  await page.goto(`/inventory/${itemId}`);
  // One page now serves both audiences, so prove the staff half is absent
  // for an anonymous viewer rather than trusting the conditional.
  await expect(page.getByText("Staff panel")).toHaveCount(0);
  await checkA11y(page);
});
