import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import { waitForHydration } from "../shared/playwright";
import { checkA11y } from "./helpers";

const __dirname = dirname(fileURLToPath(import.meta.url));

// .fixtures.json is generated by global-setup.ts: run `npm run test:accessibility` to populate it.
const { projectId, draftProjectId } = JSON.parse(
  readFileSync(join(__dirname, ".fixtures.json"), "utf-8")
) as { projectId: string; draftProjectId: string };

test.use({ storageState: join(__dirname, ".user-auth.json") });

// The listing renders a bookmark toggle per row for a signed-in viewer and
// nothing for anyone else, so the public suite's scans never see the control.
// These two are the only scans that do.

test("projects list, signed in, with bookmark controls", async ({ page }) => {
  await page.goto("/projects");
  await waitForHydration(page);
  await expect(
    page.getByRole("button", { name: /^(Bookmark|Remove bookmark)$/ }).first()
  ).toBeVisible();
  await checkA11y(page);
});

test("projects table, signed in, with bookmark controls", async ({ page }) => {
  await page.goto("/projects?view=table");
  await waitForHydration(page);
  await expect(
    page.getByRole("button", { name: /^(Bookmark|Remove bookmark)$/ }).first()
  ).toBeVisible();
  await checkA11y(page);
});

test("my projects", async ({ page }) => {
  await page.goto("/my/projects");
  await checkA11y(page);
});

test("my bookmarks", async ({ page }) => {
  await page.goto("/my/bookmarks");
  await checkA11y(page);
});

test("my items", async ({ page }) => {
  await page.goto("/my/items");
  await checkA11y(page);
});

test("@smoke my items, each tab panel", async ({ page }) => {
  await page.goto("/my/items");
  await waitForHydration(page);

  // The tab strip was three loose buttons until 2026-08-22 and this suite
  // could not tell, because a labelled button is valid markup on its own. The
  // scan that matters is of the selected state and each panel's content.
  for (const name of [/^Cart/, /^Active/, /^History/]) {
    await page.getByRole("tab", { name }).click();
    await expect(page.getByRole("tab", { name, selected: true })).toBeVisible();
    await checkA11y(page);
  }
});

test("profile page", async ({ page }) => {
  await page.goto("/profile");
  await checkA11y(page);
});

test("new project form", async ({ page }) => {
  await page.goto("/projects/new");
  await checkA11y(page);
});

test("project detail (proposer, private panel)", async ({ page }) => {
  await page.goto(`/projects/${projectId}`);
  // Prove the panel actually rendered rather than trusting the conditional:
  // this heading only exists inside ProjectPrivatePanel, which requires
  // viewerIsOwner (or viewerIsStaff) to be true.
  await expect(
    page.getByRole("heading", { name: "Private", exact: true })
  ).toBeVisible();
  await checkA11y(page);
});

test("edit project form", async ({ page }) => {
  await page.goto(`/projects/${projectId}/edit`);
  await checkA11y(page);
});

test("delete confirmation dialog", async ({ page }) => {
  await page.goto(`/projects/${draftProjectId}`);
  await waitForHydration(page);

  await page
    .getByRole("button", { name: /Delete/ })
    .first()
    .click();
  const dialog = page.getByRole("alertdialog");
  await expect(dialog).toBeVisible();

  // A native confirm() could not be scanned at all: axe cannot reach a page
  // whose script is parked on a modal browser prompt.
  await checkA11y(page);

  await page.getByRole("button", { name: "Cancel" }).click();
  await expect(dialog).toHaveCount(0);
});
