import { test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkA11y } from './helpers';

const __dirname = dirname(fileURLToPath(import.meta.url));

// .fixtures.json is generated by global-setup.ts — run `npm run test:accessibility` to populate it.
const { projectId } = JSON.parse(
  readFileSync(join(__dirname, '.fixtures.json'), 'utf-8'),
) as { projectId: string };

test.use({ storageState: join(__dirname, '.user-auth.json') });

test('my projects', async ({ page }) => {
  await page.goto('/my/projects');
  await checkA11y(page);
});

test('my bookmarks', async ({ page }) => {
  await page.goto('/my/bookmarks');
  await checkA11y(page);
});

test('my items', async ({ page }) => {
  await page.goto('/my/items');
  await checkA11y(page);
});

test('profile page', async ({ page }) => {
  await page.goto('/profile');
  await checkA11y(page);
});

test('new project form', async ({ page }) => {
  await page.goto('/projects/new');
  await checkA11y(page);
});

test('edit project form', async ({ page }) => {
  await page.goto(`/projects/${projectId}/edit`);
  await checkA11y(page);
});
