import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Locator, Response } from "@playwright/test";
import { expect, test } from "@playwright/test";
import {
  expectNoHorizontalOverflow,
  waitForHydration,
  waitForSurfaceSettled,
} from "../shared/playwright";
import { checkA11y, expectUnderlinedAtRest } from "./helpers";

const __dirname = dirname(fileURLToPath(import.meta.url));

// .fixtures.json is generated by global-setup.ts: run `npm run test:accessibility` to populate it.
const { projectId, bookmarkProjectIds, draftProjectId } = JSON.parse(
  readFileSync(join(__dirname, ".fixtures.json"), "utf-8")
) as {
  projectId: string;
  // Absent from a `.fixtures.json` written before #435, which is what the
  // throw below is for.
  bookmarkProjectIds?: string[];
  draftProjectId: string;
};

/**
 * The detail page's initial "is this bookmarked" read, by the only thing that
 * names it: a server function URL is the base64 of its module path and its
 * export.
 *
 * `BookmarkButton` renders from `useState(false)` and corrects itself when
 * that read lands, which is a window a person never hits and a test lands in
 * every time. Clicking inside it loses the click: the optimistic set is
 * overwritten by the older answer, the label goes back to "Bookmark" and the
 * write it already sent is invisible. That is a component bug (#444) and this
 * scan is not the place to prove it, so wait the window out.
 *
 * The encoding is TanStack Start's, so a framework upgrade could change it.
 * That failure is loud and lands here: the wait times out naming this
 * function, rather than passing on a read it never saw.
 */
function isInitialBookmarkRead(response: Response): boolean {
  const encoded = /\/_serverFn\/([^/?]+)/.exec(response.url())?.[1];
  if (!encoded) {
    return false;
  }
  return Buffer.from(encoded, "base64")
    .toString("utf8")
    .includes("isBookmarked");
}

/**
 * The project this parallel slot may bookmark, and no other running test may.
 *
 * The suite's only writing scan runs twice over (once per colour scheme), and
 * again per copy under `--repeat-each`, all against the same seeded student.
 * On one shared project id those copies flipped each other's toggle mid-wait
 * (#435). `parallelIndex` is Playwright's one guarantee that two tests running
 * at the same time get different values, so it is what the pool is keyed on.
 */
function bookmarkProjectIdFor(parallelIndex: number): string {
  const id = bookmarkProjectIds?.[parallelIndex];
  if (!id) {
    throw new Error(
      `No bookmark project seeded for parallel slot ${parallelIndex}. Delete src/test/a11y/.fixtures.json and re-run the suite so global-setup.ts writes one per worker.`
    );
  }
  return id;
}

test.use({ storageState: join(__dirname, ".user-auth.json") });

// The listing renders a bookmark toggle per row and a count on the title row
// for a signed-in viewer and nothing for anyone else, so the public suite's
// scans never see either control. These are the only scans that do.

test("projects list, signed in, with bookmark controls", async ({ page }) => {
  await page.goto("/projects");
  await waitForHydration(page);
  await expect(
    page.getByRole("button", { name: /^(Bookmark|Remove bookmark)$/ }).first()
  ).toBeVisible();
  await expect(page.getByRole("link", { name: /^Bookmarks/ })).toBeVisible();
  const propose = page.getByRole("link", { name: "Propose project" });
  await expect(propose).toHaveAttribute("href", "/projects/new");
  await checkA11y(page);

  // Both title-row buttons share the row at a phone width without pushing
  // the page wider than the viewport (#280).
  await page.setViewportSize({ width: 375, height: 812 });
  await expect(propose).toBeVisible();
  await expect(page.getByRole("link", { name: /^Bookmarks/ })).toBeVisible();
  await expectNoHorizontalOverflow(page);
  await checkA11y(page);

  // The table view restacks into cards at this width, and the cards fit
  // too (#300).
  await page.goto("/projects?view=table");
  await waitForHydration(page);
  await expect(page.locator(".admin-table")).toBeVisible();
  await expectNoHorizontalOverflow(page);
  await checkA11y(page);
});

/**
 * A rendered `<button>` and an `asChild` `<Link>` of the same variant and size
 * read the same at rest, on hover and on focus (UI-CONVENTIONS, "A variant
 * owns its text colour at rest" and "A button shows the hand cursor").
 *
 * The pair is `BookmarkButton` and the Edit link on a project detail page,
 * both `outline` `sm`, which is the pair the issue names and the pair the
 * pull request screenshots. Same size, so every box property is comparable
 * and not only colour: on `main` the anchor is brand orange with the
 * browser's hand cursor and the button is body colour with the arrow, so the
 * cursor told the reader which element the code had chosen rather than
 * whether the thing was clickable. jsdom computes none of this.
 */
test("@smoke an outline Button and an outline asChild Link read the same", async ({
  page,
}) => {
  await page.goto(`/projects/${projectId}`);
  await waitForHydration(page);
  const button = page.getByRole("button", {
    name: /^(Bookmark|Remove bookmark)$/,
  });
  // Scoped to the header's action row, because the page carries three Edit
  // links: this one, a full-width copy below the image for phone widths, and
  // the proposer's own panel further down. This is the one that shares a row
  // with Bookmark, which is the pair the issue names.
  const link = button.locator("xpath=..").getByRole("link", { name: "Edit" });
  await expect(button).toBeVisible();
  await expect(link).toBeVisible();

  const read = (locator: Locator) =>
    locator.evaluate((el) => {
      const s = getComputedStyle(el);
      return {
        // backgroundColor, borderColor and boxShadow are what `outline`
        // actually changes on hover and on focus-visible, so leaving them out
        // would have made those two phases assert nothing new.
        backgroundColor: s.backgroundColor,
        borderColor: s.borderColor,
        borderRadius: s.borderRadius,
        borderWidth: s.borderWidth,
        boxShadow: s.boxShadow,
        color: s.color,
        cursor: s.cursor,
        fontSize: s.fontSize,
        fontWeight: s.fontWeight,
        height: s.height,
      };
    });

  // `styles.css` transitions background, colour, border and transform over
  // 180ms on every button and anchor, so a computed value read the instant
  // after a hover is a frame partway through it, and the two controls were
  // compared at different points along the same curve. Awaiting the element's
  // own animations is the technique `waitForSurfaceSettled` already uses.
  const settle = (locator: Locator) =>
    locator.evaluate(async (el) => {
      // A frame first: a transition is constructed during the style recalc
      // that follows the state change, not synchronously with it, so sampling
      // `getAnimations()` straight after a hover can return an empty list and
      // resolve before the thing it is waiting for exists.
      await new Promise(requestAnimationFrame);
      const running = () =>
        el
          .getAnimations()
          .filter(
            (a) =>
              a.playState === "running" &&
              a.effect?.getTiming().iterations !== Number.POSITIVE_INFINITY
          );
      // Loop rather than sample once, as `waitForSurfaceSettled` does: one
      // transition finishing can leave another still going.
      for (let batch = running(); batch.length > 0; batch = running()) {
        await Promise.allSettled(batch.map((a) => a.finished));
      }
    });

  const atRest = await read(button);
  expect(await read(link)).toEqual(atRest);
  expect(atRest.cursor).toBe("pointer");

  await button.hover();
  await settle(button);
  const hovered = await read(button);
  await link.hover();
  await settle(link);
  expect(await read(link)).toEqual(hovered);

  // The pointer is still parked on the link from the hover phase, and a
  // control that is both hovered and focused reads differently from one that
  // is only focused. Park it off both before comparing focus rings.
  await page.mouse.move(0, 0);
  await settle(button);
  await settle(link);

  await button.focus();
  await settle(button);
  const focused = await read(button);
  await link.focus();
  await settle(link);
  expect(await read(link)).toEqual(focused);
});

/**
 * The pressed half of a toggle is filled, and the fill comes from
 * `aria-pressed` in the Button base class rather than a conditional class at
 * the call site (UI-CONVENTIONS, "`className` on a Button never restyles it").
 *
 * The unit test asserts the attribute, which is what a screen reader reads;
 * this asserts the attribute is also what paints, so the two cannot drift.
 * jsdom resolves no Tailwind, so it cannot see this.
 */
test("@smoke the view toggle's pressed half is filled, from aria-pressed", async ({
  page,
}) => {
  await page.goto("/projects");
  await waitForHydration(page);
  const pressed = page.getByRole("button", { name: "Card view" });
  const unpressed = page.getByRole("button", { name: "Table view" });
  await expect(pressed).toHaveAttribute("aria-pressed", "true");
  await expect(unpressed).toHaveAttribute("aria-pressed", "false");

  const background = (locator: Locator) =>
    locator.evaluate((el) => getComputedStyle(el).backgroundColor);
  expect(await background(pressed)).not.toBe(await background(unpressed));
});

test("projects table, signed in, with bookmark controls", async ({ page }) => {
  await page.goto("/projects?view=table");
  await waitForHydration(page);
  await expect(
    page.getByRole("button", { name: /^(Bookmark|Remove bookmark)$/ }).first()
  ).toBeVisible();
  await checkA11y(page);
});

test("inventory table, signed in, with borrow list controls", async ({
  page,
}) => {
  await page.goto("/inventory?view=table");
  await waitForHydration(page);
  await expect(
    page.getByRole("button", { name: /^(Borrow|In borrow list)$/ }).first()
  ).toBeVisible();
  await expect(page.getByRole("link", { name: /^Borrow list/ })).toBeVisible();
  await checkA11y(page);

  // At a phone width the table restacks into cards that fit (#300), and
  // the two title-row buttons share the row without pushing the page wider
  // than the viewport, as on /projects (#297).
  await page.setViewportSize({ width: 375, height: 812 });
  await expectNoHorizontalOverflow(page);
  await page.goto("/inventory");
  await waitForHydration(page);
  await expect(
    page.getByRole("link", { name: "Request something else" })
  ).toBeVisible();
  await expect(page.getByRole("link", { name: /^Borrow list/ })).toBeVisible();
  await expectNoHorizontalOverflow(page);
  await checkA11y(page);
});

test("my projects", async ({ page }) => {
  await page.goto("/my/projects");
  await checkA11y(page);
});

test("my bookmarks, as a table with a saved project", async ({
  page,
}, testInfo) => {
  // The seed leaves the user with no bookmarks, so an empty scan would miss
  // the table entirely. Save one from its page, scan the table, remove it,
  // and scan whatever the page shows after.
  const bookmarkProjectId = bookmarkProjectIdFor(testInfo.parallelIndex);
  // Armed before the navigation, because the read is fired by an effect that
  // runs the moment the page hydrates.
  const initialRead = page.waitForResponse(isInitialBookmarkRead);
  await page.goto(`/projects/${bookmarkProjectId}`);
  await waitForHydration(page);
  await initialRead;
  // Only now does the label mean anything. "Remove bookmark" here is a retry
  // of a run that failed after saving: global-setup clears this slot's rows
  // once per run, not once per attempt.
  const remove = page.getByRole("button", { name: "Remove bookmark" });
  if ((await remove.count()) === 0) {
    await page.getByRole("button", { name: "Bookmark", exact: true }).click();
  }
  // The label flips before the write lands and the button is disabled
  // until it does; navigating on the label alone aborts the request.
  await expect(remove).toBeEnabled();
  await page.goto("/my/bookmarks");
  await waitForHydration(page);
  await expect(page.getByRole("table", { name: "My bookmarks" })).toBeVisible();
  await checkA11y(page);

  // The row keeps its place and the toggle flips to its unset state (#420),
  // which is a surface nothing else scans: the old Remove button took the row
  // with it, so there was never an un-bookmarked row to check.
  //
  // Held by the title link, which names the row this test saved and survives
  // the click. A locator filtered on "Remove bookmark" would not: it
  // re-resolves afterwards and lands on whichever row still has one.
  const row = page
    .getByRole("row")
    .filter({ has: page.locator(`a[href="/projects/${bookmarkProjectId}"]`) });
  const before = await page.getByRole("row").count();
  await row.getByRole("button", { name: "Remove bookmark" }).click();
  // Enabled, not merely visible. `BookmarkToggle` flips its label from the
  // optimistic set update and stays disabled while the write is in flight, and
  // axe exempts a disabled control from colour contrast, so scanning on the
  // visible-only wait would skip the state this test exists to cover.
  await expect(
    row.getByRole("button", { name: "Bookmark", exact: true })
  ).toBeEnabled();
  // Not the empty state: the seeded user may hold other bookmarks, and this
  // scan must not depend on that. The count is unchanged, which is the point.
  await expect(page.getByRole("row")).toHaveCount(before);
  await checkA11y(page);
});

test("my items", async ({ page }) => {
  await page.goto("/my/items");
  await checkA11y(page);
});

test("@smoke my items, each filter", async ({ page }) => {
  await page.goto("/my/items");
  await waitForHydration(page);
  // The unread badge on the bell is fetched after hydration, so a scan taken
  // at `load` never sees it, which is how its dark-mode contrast went
  // unchecked until #145. Waiting for the count puts the badge in every scan
  // below. One caveat axe imposes: a single-character badge is skipped as too
  // short to be judged as text, so only a count of ten or more ("9+") is
  // measured. The seed leaves this user short of that, so this wait proves the
  // badge is present, not that its colours pass.
  await expect(
    page.getByRole("button", { name: "Notifications" }).getByText(/^\d+\+?$/)
  ).toBeVisible();

  // One grouped table under a filter, since 2026-09-09. Each filter renders
  // a different set of groups, and the group headers are `th` elements
  // inside the body, which is the markup this scan exists to check. The
  // select is driven by URL rather than by clicking, because the scan is of
  // the rendered page, not of the Radix menu.
  for (const filter of ["open", "closed", "all"]) {
    await page.goto(`/my/items?filter=${filter}`);
    await waitForHydration(page);
    await expect(page.getByRole("table", { name: "My items" })).toBeVisible();
    await checkA11y(page);
  }
  // The sheet, open: a dialog beside the table with the line's timeline.
  await page.getByRole("button", { name: "Details" }).first().click();
  await waitForSurfaceSettled(page.getByRole("dialog"));
  await checkA11y(page);
});

test("my items opens by saying what needs attention", async ({ page }) => {
  await page.goto("/my/items");
  await waitForHydration(page);
  // global-setup gives this user an overdue hold, so the region renders with
  // its counts and its link into Active, and a borrow-list item, so the
  // Borrow list tab shows the assembled request rather than the empty state.
  const region = page.getByRole("region", { name: "Needs your attention" });
  await expect(region).toBeVisible();
  const below = region.getByRole("link", { name: /below/ });
  await expect(below).toBeVisible();
  // The one link in the callout is body copy under a list (#364).
  await expectUnderlinedAtRest(below);
  // The borrow list is the first group, with Submit on its header and the
  // dialog that carries the note behind it.
  await expect(page.getByText("Not submitted yet")).toBeVisible();
  await page.getByRole("button", { name: "Submit" }).click();
  await waitForSurfaceSettled(
    page.getByRole("dialog", { name: /as one request/ })
  );
  await expect(page.getByLabel("Note for staff (optional)")).toBeVisible();
  await checkA11y(page);
});

test("profile page", async ({ page }) => {
  await page.goto("/profile");
  await checkA11y(page);
});

test("new project form", async ({ page }) => {
  await page.goto("/projects/new");
  await checkA11y(page);
});

test("project detail (proposer, private panel)", async ({ page }) => {
  await page.goto(`/projects/${projectId}`);
  // Prove the panel actually rendered rather than trusting the conditional:
  // this heading only exists inside ProjectPrivatePanel, which requires
  // viewerIsOwner (or viewerIsStaff) to be true.
  await expect(
    page.getByRole("heading", { name: "Private", exact: true })
  ).toBeVisible();
  await checkA11y(page);
});

test("edit project form", async ({ page }) => {
  await page.goto(`/projects/${projectId}/edit`);
  await checkA11y(page);
});

test("delete confirmation dialog", async ({ page }) => {
  await page.goto(`/projects/${draftProjectId}`);
  await waitForHydration(page);

  await page
    .getByRole("button", { name: /Delete/ })
    .first()
    .click();
  const dialog = page.getByRole("alertdialog");
  await waitForSurfaceSettled(dialog);

  // A native confirm() could not be scanned at all: axe cannot reach a page
  // whose script is parked on a modal browser prompt.
  await checkA11y(page);

  await page.getByRole("button", { name: "Cancel" }).click();
  await expect(dialog).toHaveCount(0);
});
