/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as InventoryItemIdRouteImport } from './routes/inventory/$itemId'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedProjectsNewRouteImport } from './routes/_authed/projects/new'
import { Route as AuthedMyProjectsRouteImport } from './routes/_authed/my/projects'
import { Route as AuthedMyItemsRouteImport } from './routes/_authed/my/items'
import { Route as AuthedMyBookmarksRouteImport } from './routes/_authed/my/bookmarks'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users/index'
import { Route as AuthedAdminProjectsIndexRouteImport } from './routes/_authed/admin/projects/index'
import { Route as AuthedAdminProgramsIndexRouteImport } from './routes/_authed/admin/programs/index'
import { Route as AuthedAdminMentorsIndexRouteImport } from './routes/_authed/admin/mentors/index'
import { Route as AuthedAdminInventoryIndexRouteImport } from './routes/_authed/admin/inventory/index'
import { Route as AuthedAdminCategoriesIndexRouteImport } from './routes/_authed/admin/categories/index'
import { Route as AuthedProjectsProjectIdEditRouteImport } from './routes/_authed/projects/$projectId/edit'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed/admin/users/$userId'
import { Route as AuthedAdminProgramsProgramIdRouteImport } from './routes/_authed/admin/programs/$programId'
import { Route as AuthedAdminInventoryRequestsRouteImport } from './routes/_authed/admin/inventory/requests'
import { Route as AuthedAdminInventoryNewRouteImport } from './routes/_authed/admin/inventory/new'
import { Route as AuthedAdminInventoryItemIdRouteImport } from './routes/_authed/admin/inventory/$itemId'
import { Route as AuthedAdminCategoriesCategoryIdRouteImport } from './routes/_authed/admin/categories/$categoryId'
import { Route as AuthedAdminInventoryItemIdEditRouteImport } from './routes/_authed/admin/inventory/$itemId.edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsNewRoute = AuthedProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyProjectsRoute = AuthedMyProjectsRouteImport.update({
  id: '/my/projects',
  path: '/my/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyItemsRoute = AuthedMyItemsRouteImport.update({
  id: '/my/items',
  path: '/my/items',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyBookmarksRoute = AuthedMyBookmarksRouteImport.update({
  id: '/my/bookmarks',
  path: '/my/bookmarks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminProjectsIndexRoute =
  AuthedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminProgramsIndexRoute =
  AuthedAdminProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminMentorsIndexRoute = AuthedAdminMentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminInventoryIndexRoute =
  AuthedAdminInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminCategoriesIndexRoute =
  AuthedAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedProjectsProjectIdEditRoute =
  AuthedProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminProgramsProgramIdRoute =
  AuthedAdminProgramsProgramIdRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminInventoryRequestsRoute =
  AuthedAdminInventoryRequestsRouteImport.update({
    id: '/inventory/requests',
    path: '/inventory/requests',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminInventoryNewRoute = AuthedAdminInventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminInventoryItemIdRoute =
  AuthedAdminInventoryItemIdRouteImport.update({
    id: '/inventory/$itemId',
    path: '/inventory/$itemId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminCategoriesCategoryIdRoute =
  AuthedAdminCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminInventoryItemIdEditRoute =
  AuthedAdminInventoryItemIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedAdminInventoryItemIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/my/bookmarks': typeof AuthedMyBookmarksRoute
  '/my/items': typeof AuthedMyItemsRoute
  '/my/projects': typeof AuthedMyProjectsRoute
  '/projects/new': typeof AuthedProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/categories/$categoryId': typeof AuthedAdminCategoriesCategoryIdRoute
  '/admin/inventory/$itemId': typeof AuthedAdminInventoryItemIdRouteWithChildren
  '/admin/inventory/new': typeof AuthedAdminInventoryNewRoute
  '/admin/inventory/requests': typeof AuthedAdminInventoryRequestsRoute
  '/admin/programs/$programId': typeof AuthedAdminProgramsProgramIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/projects/$projectId/edit': typeof AuthedProjectsProjectIdEditRoute
  '/admin/categories/': typeof AuthedAdminCategoriesIndexRoute
  '/admin/inventory/': typeof AuthedAdminInventoryIndexRoute
  '/admin/mentors/': typeof AuthedAdminMentorsIndexRoute
  '/admin/programs/': typeof AuthedAdminProgramsIndexRoute
  '/admin/projects/': typeof AuthedAdminProjectsIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/admin/inventory/$itemId/edit': typeof AuthedAdminInventoryItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/profile': typeof AuthedProfileRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/my/bookmarks': typeof AuthedMyBookmarksRoute
  '/my/items': typeof AuthedMyItemsRoute
  '/my/projects': typeof AuthedMyProjectsRoute
  '/projects/new': typeof AuthedProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/categories/$categoryId': typeof AuthedAdminCategoriesCategoryIdRoute
  '/admin/inventory/$itemId': typeof AuthedAdminInventoryItemIdRouteWithChildren
  '/admin/inventory/new': typeof AuthedAdminInventoryNewRoute
  '/admin/inventory/requests': typeof AuthedAdminInventoryRequestsRoute
  '/admin/programs/$programId': typeof AuthedAdminProgramsProgramIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/projects/$projectId/edit': typeof AuthedProjectsProjectIdEditRoute
  '/admin/categories': typeof AuthedAdminCategoriesIndexRoute
  '/admin/inventory': typeof AuthedAdminInventoryIndexRoute
  '/admin/mentors': typeof AuthedAdminMentorsIndexRoute
  '/admin/programs': typeof AuthedAdminProgramsIndexRoute
  '/admin/projects': typeof AuthedAdminProjectsIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
  '/admin/inventory/$itemId/edit': typeof AuthedAdminInventoryItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authed/my/bookmarks': typeof AuthedMyBookmarksRoute
  '/_authed/my/items': typeof AuthedMyItemsRoute
  '/_authed/my/projects': typeof AuthedMyProjectsRoute
  '/_authed/projects/new': typeof AuthedProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/categories/$categoryId': typeof AuthedAdminCategoriesCategoryIdRoute
  '/_authed/admin/inventory/$itemId': typeof AuthedAdminInventoryItemIdRouteWithChildren
  '/_authed/admin/inventory/new': typeof AuthedAdminInventoryNewRoute
  '/_authed/admin/inventory/requests': typeof AuthedAdminInventoryRequestsRoute
  '/_authed/admin/programs/$programId': typeof AuthedAdminProgramsProgramIdRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/projects/$projectId/edit': typeof AuthedProjectsProjectIdEditRoute
  '/_authed/admin/categories/': typeof AuthedAdminCategoriesIndexRoute
  '/_authed/admin/inventory/': typeof AuthedAdminInventoryIndexRoute
  '/_authed/admin/mentors/': typeof AuthedAdminMentorsIndexRoute
  '/_authed/admin/programs/': typeof AuthedAdminProgramsIndexRoute
  '/_authed/admin/projects/': typeof AuthedAdminProjectsIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/_authed/admin/inventory/$itemId/edit': typeof AuthedAdminInventoryItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/admin'
    | '/profile'
    | '/api/healthz'
    | '/inventory/$itemId'
    | '/projects/$projectId'
    | '/inventory/'
    | '/projects/'
    | '/my/bookmarks'
    | '/my/items'
    | '/my/projects'
    | '/projects/new'
    | '/api/auth/$'
    | '/admin/'
    | '/admin/categories/$categoryId'
    | '/admin/inventory/$itemId'
    | '/admin/inventory/new'
    | '/admin/inventory/requests'
    | '/admin/programs/$programId'
    | '/admin/users/$userId'
    | '/projects/$projectId/edit'
    | '/admin/categories/'
    | '/admin/inventory/'
    | '/admin/mentors/'
    | '/admin/programs/'
    | '/admin/projects/'
    | '/admin/users/'
    | '/admin/inventory/$itemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/profile'
    | '/api/healthz'
    | '/inventory/$itemId'
    | '/projects/$projectId'
    | '/inventory'
    | '/projects'
    | '/my/bookmarks'
    | '/my/items'
    | '/my/projects'
    | '/projects/new'
    | '/api/auth/$'
    | '/admin'
    | '/admin/categories/$categoryId'
    | '/admin/inventory/$itemId'
    | '/admin/inventory/new'
    | '/admin/inventory/requests'
    | '/admin/programs/$programId'
    | '/admin/users/$userId'
    | '/projects/$projectId/edit'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/mentors'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/inventory/$itemId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/_authed/admin'
    | '/_authed/profile'
    | '/api/healthz'
    | '/inventory/$itemId'
    | '/projects/$projectId'
    | '/inventory/'
    | '/projects/'
    | '/_authed/my/bookmarks'
    | '/_authed/my/items'
    | '/_authed/my/projects'
    | '/_authed/projects/new'
    | '/api/auth/$'
    | '/_authed/admin/'
    | '/_authed/admin/categories/$categoryId'
    | '/_authed/admin/inventory/$itemId'
    | '/_authed/admin/inventory/new'
    | '/_authed/admin/inventory/requests'
    | '/_authed/admin/programs/$programId'
    | '/_authed/admin/users/$userId'
    | '/_authed/projects/$projectId/edit'
    | '/_authed/admin/categories/'
    | '/_authed/admin/inventory/'
    | '/_authed/admin/mentors/'
    | '/_authed/admin/programs/'
    | '/_authed/admin/projects/'
    | '/_authed/admin/users/'
    | '/_authed/admin/inventory/$itemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  InventoryItemIdRoute: typeof InventoryItemIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/new': {
      id: '/_authed/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthedProjectsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my/projects': {
      id: '/_authed/my/projects'
      path: '/my/projects'
      fullPath: '/my/projects'
      preLoaderRoute: typeof AuthedMyProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my/items': {
      id: '/_authed/my/items'
      path: '/my/items'
      fullPath: '/my/items'
      preLoaderRoute: typeof AuthedMyItemsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my/bookmarks': {
      id: '/_authed/my/bookmarks'
      path: '/my/bookmarks'
      fullPath: '/my/bookmarks'
      preLoaderRoute: typeof AuthedMyBookmarksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/projects/': {
      id: '/_authed/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/programs/': {
      id: '/_authed/admin/programs/'
      path: '/programs'
      fullPath: '/admin/programs/'
      preLoaderRoute: typeof AuthedAdminProgramsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/mentors/': {
      id: '/_authed/admin/mentors/'
      path: '/mentors'
      fullPath: '/admin/mentors/'
      preLoaderRoute: typeof AuthedAdminMentorsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/inventory/': {
      id: '/_authed/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AuthedAdminInventoryIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/categories/': {
      id: '/_authed/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/projects/$projectId/edit': {
      id: '/_authed/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthedProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/programs/$programId': {
      id: '/_authed/admin/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/admin/programs/$programId'
      preLoaderRoute: typeof AuthedAdminProgramsProgramIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/inventory/requests': {
      id: '/_authed/admin/inventory/requests'
      path: '/inventory/requests'
      fullPath: '/admin/inventory/requests'
      preLoaderRoute: typeof AuthedAdminInventoryRequestsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/inventory/new': {
      id: '/_authed/admin/inventory/new'
      path: '/inventory/new'
      fullPath: '/admin/inventory/new'
      preLoaderRoute: typeof AuthedAdminInventoryNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/inventory/$itemId': {
      id: '/_authed/admin/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/admin/inventory/$itemId'
      preLoaderRoute: typeof AuthedAdminInventoryItemIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/categories/$categoryId': {
      id: '/_authed/admin/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AuthedAdminCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/inventory/$itemId/edit': {
      id: '/_authed/admin/inventory/$itemId/edit'
      path: '/edit'
      fullPath: '/admin/inventory/$itemId/edit'
      preLoaderRoute: typeof AuthedAdminInventoryItemIdEditRouteImport
      parentRoute: typeof AuthedAdminInventoryItemIdRoute
    }
  }
}

interface AuthedAdminInventoryItemIdRouteChildren {
  AuthedAdminInventoryItemIdEditRoute: typeof AuthedAdminInventoryItemIdEditRoute
}

const AuthedAdminInventoryItemIdRouteChildren: AuthedAdminInventoryItemIdRouteChildren =
  {
    AuthedAdminInventoryItemIdEditRoute: AuthedAdminInventoryItemIdEditRoute,
  }

const AuthedAdminInventoryItemIdRouteWithChildren =
  AuthedAdminInventoryItemIdRoute._addFileChildren(
    AuthedAdminInventoryItemIdRouteChildren,
  )

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminCategoriesCategoryIdRoute: typeof AuthedAdminCategoriesCategoryIdRoute
  AuthedAdminInventoryItemIdRoute: typeof AuthedAdminInventoryItemIdRouteWithChildren
  AuthedAdminInventoryNewRoute: typeof AuthedAdminInventoryNewRoute
  AuthedAdminInventoryRequestsRoute: typeof AuthedAdminInventoryRequestsRoute
  AuthedAdminProgramsProgramIdRoute: typeof AuthedAdminProgramsProgramIdRoute
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminCategoriesIndexRoute: typeof AuthedAdminCategoriesIndexRoute
  AuthedAdminInventoryIndexRoute: typeof AuthedAdminInventoryIndexRoute
  AuthedAdminMentorsIndexRoute: typeof AuthedAdminMentorsIndexRoute
  AuthedAdminProgramsIndexRoute: typeof AuthedAdminProgramsIndexRoute
  AuthedAdminProjectsIndexRoute: typeof AuthedAdminProjectsIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminCategoriesCategoryIdRoute: AuthedAdminCategoriesCategoryIdRoute,
  AuthedAdminInventoryItemIdRoute: AuthedAdminInventoryItemIdRouteWithChildren,
  AuthedAdminInventoryNewRoute: AuthedAdminInventoryNewRoute,
  AuthedAdminInventoryRequestsRoute: AuthedAdminInventoryRequestsRoute,
  AuthedAdminProgramsProgramIdRoute: AuthedAdminProgramsProgramIdRoute,
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminCategoriesIndexRoute: AuthedAdminCategoriesIndexRoute,
  AuthedAdminInventoryIndexRoute: AuthedAdminInventoryIndexRoute,
  AuthedAdminMentorsIndexRoute: AuthedAdminMentorsIndexRoute,
  AuthedAdminProgramsIndexRoute: AuthedAdminProgramsIndexRoute,
  AuthedAdminProjectsIndexRoute: AuthedAdminProjectsIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedMyBookmarksRoute: typeof AuthedMyBookmarksRoute
  AuthedMyItemsRoute: typeof AuthedMyItemsRoute
  AuthedMyProjectsRoute: typeof AuthedMyProjectsRoute
  AuthedProjectsNewRoute: typeof AuthedProjectsNewRoute
  AuthedProjectsProjectIdEditRoute: typeof AuthedProjectsProjectIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedMyBookmarksRoute: AuthedMyBookmarksRoute,
  AuthedMyItemsRoute: AuthedMyItemsRoute,
  AuthedMyProjectsRoute: AuthedMyProjectsRoute,
  AuthedProjectsNewRoute: AuthedProjectsNewRoute,
  AuthedProjectsProjectIdEditRoute: AuthedProjectsProjectIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  InventoryItemIdRoute: InventoryItemIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
